# Site settings
title: alexisjanvier.net
email: contact@alexisjanvier.net
description: "Ici le description du site, à voir pour plus tard"
baseurl: ""
url: "http://alexisjanvier.net"
twitter_username: alexisjanvier
github_username:  alexisjanvier

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
